apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tetsuya28
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      serviceAccountName: ""
      containers:
      - name: app
        image: ""
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        startupProbe:
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
      - image: ""
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
        startupProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
          httpGet:
            path: /
